export const FETCH_COMMANDE_REQUEST = 'FETCH_COMMANDE_REQUEST';
export const FETCH_COMMANDE_SUCCESS = 'FETCH_COMMANDE_SUCCESS';
export const FETCH_COMMANDE_FAILURE = 'FETCH_COMMANDE_FAILURE';

export const UPDATE_COMMANDE_REQUEST = 'UPDATE_COMMANDE_REQUEST';
export const UPDATE_COMMANDE_SUCCESS = 'UPDATE_COMMANDE_SUCCESS';
export const UPDATE_COMMANDE_FAILURE = 'UPDATE_COMMANDE_FAILURE';


export const DELETE_COMMANDE_REQUEST = 'DELETE_COMMANDE_REQUEST';
export const DELETE_COMMANDE_SUCCESS = 'DELETE_COMMANDE_SUCCESS';
export const DELETE_COMMANDE_FAILURE = 'DELETE_COMMANDE_FAILURE';

export const ADD_COMMANDE_SUCCESS = 'ADD_COMMANDE_SUCCESS';
export const ADD_COMMANDE_FAILURE = 'ADD_COMMANDE_FAILURE';
export const ADD_COMMANDE_REQUEST = 'ADD_COMMANDE_REQUEST';