//fetch plat
export const FETCH_PLAT_SUCCESS = 'FETCH_PLAT_SUCCESS';
export const FETCH_PLAT_FAILURE = 'FETCH_PLAT_FAILURE';
export const FETCH_PLAT_REQUEST = 'FETCH_PLAT_REQUEST';

//update plat
export const UPDATE_PLAT_SUCCESS = 'UPDATE_PLAT_SUCCESS';
export const UPDATE_PLAT_FAILURE = 'UPDATE_PLAT_FAILURE';
export const UPDATE_PLAT_REQUEST = 'UPDATE_PLAT_REQUEST';

//delete plat
export const DELETE_PLAT_SUCCESS = 'DELETE_PLAT_SUCCESS';
export const DELETE_PLAT_FAILURE = 'DELETE_PLAT_FAILURE';
export const DELETE_PLAT_REQUEST = 'DELETE_PLAT_REQUEST';


//plat du jour

export const FETCH_PLAT_JOUR_SUCCESS = 'FETCH_PLAT_JOUR_SUCCESS';
export const FETCH_PLAT_JOUR_FAILURE = 'FETCH_PLAT_JOUR_FAILURE';
export const FETCH_PLAT_JOUR_REQUEST = 'FETCH_PLAT_JOUR_REQUEST';
